name: icon_example
description: Example usage of IconToo widget from Icon package.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  icon:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - fonts/
  fonts:
    - family: BashinBugs-Stripped
      fonts:
        - asset: fonts/BashinBugs-Stripped.otf
