name: icon_example
description: Example usage of IconToo widget and Icon/Too operator utilities from package:icon.
publish_to: 'none'
version: 2.2.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  icon:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - fonts/
  fonts:
    # Font with custom non-square icon
    - family: BashinBugs-Stripped
      fonts:
        - asset: fonts/BashinBugs-Stripped.otf
