name: icon
description: An extended Icon "too" for those that are not actually square, plus shadows support + neat Icon extension operators.
version: 2.2.1
repository: https://github.com/Zabadam/icon
issue_tracker: https://github.com/Zabadam/icon/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
